### POST para sing up
POST https://dam-api-ribg.onrender.com/create_account
Content-Type: application/json

{
  "email": "user6@email.com",
  "password": "123qwe#"
}
### POST para sing in
POST https://dam-api-ribg.onrender.com/login
Content-Type: application/json

{
  "email": "user5@email.com",
  "password": "123qwe#"
}
### GET com Token no Header
GET https://dam-api-ribg.onrender.com/listuserplants  
Authorization: Bearer XOwCOfubPXXAuIDmi-wDrR0wRsRcTtd1vXuv9DZooQE
### POST com JSON e Token no Header
POST https://dam-api-ribg.onrender.com/createplant
Authorization: Bearer XOwCOfubPXXAuIDmi-wDrR0wRsRcTtd1vXuv9DZooQE
Content-Type: application/json

{
  "name": "Rose",
  "species": "Rosa damascena",
  "description": "A beautiful red rose"
}

### POST com JSON e Token no Header
PUT https://dam-api-ribg.onrender.com/editplant
Authorization: Bearer XOwCOfubPXXAuIDmi-wDrR0wRsRcTtd1vXuv9DZooQE
Content-Type: application/json

{
  "id": 2,
  "name": "Tulip",
  "species": "Tulipa gesneriana",
  "description": "A vibrant yellow tulip"
}
### DELETE com JSON e Token no Header
DELETE https://dam-api-ribg.onrender.com/deleteplant
Authorization: Bearer XOwCOfubPXXAuIDmi-wDrR0wRsRcTtd1vXuv9DZooQE
Content-Type: application/json

{
  "id": 3
}

### GET com Token no Header
POST https://dam-api-ribg.onrender.com/sensor_reading
Content-Type: application/json

{
  "plant_id": 2,
  "humidity": 80.5,
  "light": 45.7
}
### POST com JSON
GET https://dam-api-ribg.onrender.com/readings
Content-Type: application/json

{
  "plant_id": 2,
  "start_time": "2025-12-20T00:00:00Z",
  "end_time": "2025-12-22T00:00:00Z"
}

